spring.application.name=arzum-iletisim

spring.datasource.url=jdbc:mysql://localhost:3306/arzum_db
spring.datasource.username=root
spring.datasource.password=ysnkckr1903

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.thymeleaf.cache=false
